name: attendance_app
description: מערכת שעון נוכחות ודיווח עבור עובדי החברה
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  share_plus: ^6.3.0
  csv: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
